# Generated by Django 4.2.7 on 2025-11-12 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0013_customuser"),
        ("admin", "0004_alter_logentry_user"),
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="auth.customuser"
            ),
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
