# Generated by Django 4.2.7 on 2025-11-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="room_images/",
                verbose_name="Room Specific Image",
            ),
        ),
    ]
