# Generated by Django 4.2.7 on 2025-11-02 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_number',
        ),
        migrations.AlterField(
            model_name='room',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.city'),
        ),
    ]
