# Generated by Django 4.2.7 on 2025-11-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.IntegerField(
                blank=True, help_text="8-digit phone number", null=True
            ),
        ),
    ]
