# Generated by Django 4.2.7 on 2025-11-10 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0002_room_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterField(
            model_name="room",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room",
                to="hotel.city",
            ),
        ),
    ]
