# Generated by Django 4.2.7 on 2025-11-09 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0002_alter_city_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="faq",
            options={"ordering": ["order", "category"]},
        ),
        migrations.AlterModelOptions(
            name="jobapplication",
            options={"ordering": ["-applied_date"]},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["city", "room_type"]},
        ),
        migrations.AlterModelOptions(
            name="roomtype",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="booking",
            name="total_price",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="available_start_date",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="expected_salary",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="linkedin_url",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="portfolio_url",
        ),
        migrations.RemoveField(
            model_name="joblisting",
            name="benefits",
        ),
        migrations.RemoveField(
            model_name="joblisting",
            name="responsibilities",
        ),
        migrations.AddField(
            model_name="booking",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="hotel.room",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("checked_in", "Checked In"),
                    ("checked_out", "Checked Out"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="faq",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("booking", "Booking"),
                    ("payment", "Payment"),
                    ("facilities", "Facilities"),
                    ("cancellation", "Cancellation"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="cover_letter",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="hotel.joblisting",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("under_review", "Under Review"),
                    ("interview", "Interview"),
                    ("rejected", "Rejected"),
                    ("hired", "Hired"),
                ],
                default="applied",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_listings",
                to="hotel.department",
            ),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("entry", "Entry Level"),
                    ("mid", "Mid Level"),
                    ("senior", "Senior Level"),
                    ("executive", "Executive"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("contract", "Contract"),
                    ("temporary", "Temporary"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="room",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="hotel.city",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="hotel.roomtype",
            ),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="capacity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="rooms/"),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="price_per_night",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
