# Generated by Django 4.2.7 on 2025-11-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0003_alter_userprofile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="total_guests",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("checked_in", "Checked In"),
                    ("checked_out", "Checked Out"),
                    ("cancelled", "Cancelled"),
                ],
                default="confirmed",
                max_length=20,
            ),
        ),
    ]
