# Generated by Django 4.2.7 on 2025-11-09 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0003_alter_booking_options_alter_faq_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={},
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hotel.roomtype"
            ),
        ),
    ]
