# Generated by Django 4.2.7 on 2025-11-11 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0003_alter_booking_options_alter_room_city"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "City", "verbose_name_plural": "Cities"},
        ),
    ]
