# Generated by Django 4.2.7 on 2025-11-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0004_booking_total_guests_alter_booking_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "subject",
                    models.CharField(default="General Inquiry", max_length=200),
                ),
                ("message", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this submission"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Submission",
                "verbose_name_plural": "Contact Submissions",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
