# Generated by Django 4.2.7 on 2025-11-11 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0004_alter_city_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="faq",
            options={
                "ordering": ["order", "category"],
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
            },
        ),
        migrations.AlterField(
            model_name="city",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/city/"),
        ),
        migrations.AlterField(
            model_name="room",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="hotel.city",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/room_specific/",
                verbose_name="Room Specific Image",
            ),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/room/"),
        ),
    ]
